routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('films', 'FilmController');
Route::resource('categories', 'CategoryController', [
    'only' => ['index', 'show', 'create', 'store']
]);

Route::prefix('reviews')->group(function() {
  Route::get('create/{film}', 'ReviewController@create')->name('reviews.create');
  Route::post('create/{film}', 'ReviewController@store')->name('reviews.store');
});

Route::resource('reviews', 'ReviewController', [
  'except' => ['index', 'create', 'store']
]);

Route::prefix('comments')->group(function() {
  Route::get('create/{review}', 'CommentsController@create')->name('comments.create');
  Route::post('create/{review}', 'CommentsController@store')->name('comments.store');
  Route::get('delete/{comment}', 'CommentsController@destroy')->name('comments.delete');
});

Route::resource('comments', 'CommentsController', [
  'only' => ['edit', 'update', 'destroy']
]);

Route::prefix('users')->group(function() {
  Route::get('{user}', 'UserController@show')->name('users.show');
  Route::get('edit/{user}', 'UserController@edit')->name('users.edit');
  Route::post('{user}', 'UserController@update')->name('users.update');
});

Route::get('top', 'RankController@index')->name('ranks.index');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
  protected $fillable = ['name'];

  public function films()
  {
    return $this->hasMany(Film::class);
  }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.index')->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|min:3'
        ]);

        Category::create(['name' => $request->name]);
        session()->flash('success', "Kategoria została dodana do systemu poprawnie.");
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('categories.show')->with('category', $category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">{{ __('Dodawanie kategorii') }}</div>
        <div class="card-body">
          <form method="POST" action="{{ route('categories.store') }}" >
            @csrf
            <div class="form-group row">
              <label class="col-sm-4 col-form-label">Nazwa</label>
              <div class="col-sm-8">
                <input type="text" name="name" placeholder="nowa kategoria" value="{{ old('name') }}" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}">
                @if ($errors->has('name'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('name') }}</strong>
                  </div>
                @endif
              </div>
            </div>
            <div class="form-group row mb-0">
              <div class="col-md-8 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {{ __('Utwórz') }}
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
  <h2>Kategorie filmów <hr></h2>
  <div class="card-columns">
    @each('categories.single', $categories, 'category')
  </div>
</div>

@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container mb-5">
  <h2>{{ $category->name }} <small>&mdash; filmy kategorii</small><hr></h2>
  <div class="card-columns m-2">
    @each('films.single', $category->films, 'film', 'films.empty')
  </div>
</div>
@endsection

resources/views/categories/single.blade.php
<a class="card bg-secondary text-white" href="{{ route('categories.show', [$category]) }}">
  <div class="card-header">{{ $category->name }}</div>
</a>