routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('films', 'FilmController');
Route::resource('categories', 'CategoryController', [
    'only' => ['index', 'show', 'create', 'store']
]);

Route::prefix('reviews')->group(function() {
  Route::get('create/{film}', 'ReviewController@create')->name('reviews.create');
  Route::post('create/{film}', 'ReviewController@store')->name('reviews.store');
});

Route::resource('reviews', 'ReviewController', [
  'except' => ['index', 'create', 'store']
]);

Route::prefix('comments')->group(function() {
  Route::get('create/{review}', 'CommentsController@create')->name('comments.create');
  Route::post('create/{review}', 'CommentsController@store')->name('comments.store');
  Route::get('delete/{comment}', 'CommentsController@destroy')->name('comments.delete');
});

Route::resource('comments', 'CommentsController', [
  'only' => ['edit', 'update', 'destroy']
]);

Route::prefix('users')->group(function() {
  Route::get('{user}', 'UserController@show')->name('users.show');
  Route::get('edit/{user}', 'UserController@edit')->name('users.edit');
  Route::post('{user}', 'UserController@update')->name('users.update');
});

Route::get('top', 'RankController@index')->name('ranks.index');

app/Film.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
  protected $fillable = ['title', 'genre', 'director', 'release_date', 'imgcover', 'category_id'];

  public function reviews()
  {
    return $this->hasMany(Review::class);
  }

  public function review()
  {
    return $this->hasOne(Review::class)->where('user_id', auth()->user()->id);
  }

  public function category()
  {
    return $this->belongsTo(Category::class);
  }
}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Film;

class FilmController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('films.index')->with('films', Film::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('films.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|min:3',
            'released' => 'required|date_format:"Y-m-d"',
            'genre' => 'required|string',
            'director' => 'required|string',
            'category' => 'required|integer',
            'cover' => 'required|image'
        ]);

        $movie = Film::create([
            'title' => $request->title,
            'genre' => $request->genre,
            'director' => $request->director,
            'release_date' => $request->released,
            'category_id' => $request->category,
            'imgcover' => $request->file('cover')->store('covers')
        ]);

        session()->flash('success', "Dodano nowy film do bazy danych.");
        return redirect()->route('films.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Film $film)
    {
        return view('films.show')->with('film', $film);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Film $film)
    {
        return view('films.edit', $film);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/films/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">{{ __('Tworzenie filmu') }}</div>

        <div class="card-body">
          <form method="POST" action="{{ route('films.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group row">
              <label class="col-sm-4 col-form-label">Tytuł</label>
              <div class="col-sm-8">
                <input type="text" name="title" placeholder="tytuł" value="{{ old('title') }}" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}">
                @if ($errors->has('title'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('title') }}</strong>
                  </div>
                @endif
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-4 col-form-label">Premiera</label>
              <div class="col-sm-8">
                <input type="text" name="released" placeholder="rrrr-mm-dd" value="{{ old('released') }}" class="form-control{{ $errors->has('released') ? ' is-invalid' : '' }}">
                @if ($errors->has('released'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('released') }}</strong>
                  </div>
                @endif
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-4 col-form-label">Gatunek</label>
              <div class="col-sm-8">
                <input type="text" name="genre" placeholder="gatunek" value="{{ old('genre') }}" class="form-control{{ $errors->has('genre') ? ' is-invalid' : '' }}">
                @if ($errors->has('genre'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('genre') }}</strong>
                  </div>
                @endif
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-4 col-form-label">Reżyseria</label>
              <div class="col-sm-8">
                <input type="text" name="director" placeholder="reżyseria" value="{{ old('director') }}" class="form-control{{ $errors->has('director') ? ' is-invalid' : '' }}">
                @if ($errors->has('director'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('director') }}</strong>
                  </div>
                @endif
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-4 col-form-label">Kategoria</label>
              <div class="col-sm-8">
                <select name="category" class="custom-select{{ $errors->has('category') ? ' is-invalid' : '' }}">
                  <option disabled="disabled"{{ old('category', null) ? '' : ' selected' }}>Wybierz kategorię..</option>
                  @foreach(\App\Category::all() as $category)
                    <option{{ old('category') == $category->id ? ' selected' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
                  @endforeach
                </select>
                @if ($errors->has('category'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('category') }}</strong>
                  </div>
                @endif
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-4 col-form-label">Okładka</label>
              <div class="col-sm-8">
                <div class="custom-file">
                  <input type="file" name="cover" class="custom-file-input{{ $errors->has('cover') ? ' is-invalid' : '' }}">
                  <label class="custom-file-label">Wybierz grafikę..</label>
                  @if ($errors->has('cover'))
                    <div class="invalid-feedback">
                      <strong>{{ $errors->first('cover') }}</strong>
                    </div>
                  @endif
                </div>
              </div>
            </div>

            <div class="form-group row mb-0">
              <div class="col-md-8 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {{ __('Utwórz film') }}
                </button>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/films/empty.blade.php
<div class="alert alert-light card" role="alert">
  <i class="far fa-frown mr-1"></i> Brak filmów do wyświetlenia
</div>

resources/views/films/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container mb-5">
  <h2>Baza filmów<hr></h2>
  <div class="card-columns m-2">
    @each('films.single', $films, 'film', 'films.empty')
  </div>
</div>
@endsection

resources/views/films/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <h3 class="my-4">
    O filmie<hr class="m-0">
  </h3>
  <div class="row">
    <div class="col col-sm-auto">
      <img src="/{{ $film->imgcover }}" class="movie-cover rounded" alt="Movie cover">
    </div>
    <div class="col">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <h4 class="d-inline mr-1">{{ $film->title }}</h4>
          <a href="{{ route('categories.show', $film->category) }}" class="badge text-muted">{{ $film->category->name }}</a>
        </li>
        <li class="list-group-item">
          <i class="fas fa-podcast text-muted mr-2"></i> {{ $film->director }}
        </li>
        <li class="list-group-item">
          <i class="fas fa-film text-muted mr-2"></i> {{ $film->genre }}
        </li>
        <li class="list-group-item">
          <i class="far fa-calendar text-muted mr-2"></i> {{ $film->release_date }}
        </li>
      </ul>
    </div>
  </div>

  <h5 class="mt-5">
    <i class="far fa-edit mr-2 text-muted"></i> Recenzje
    <small>
      @auth
        @if($film->review)
          <a class="float-right text-info m-1" href="{{ route('reviews.show', $film->review) }}">
            <i class="far fa-arrow-right mr-2"></i> Moja recenzja
          </a>
        @else
          <a class="float-right text-secondary m-1" href="{{ route('reviews.create', $film) }}">
            <i class="far fa-plus mr-2"></i> Zrecenzuj..
          </a>
        @endif
      @endauth
    </small>
    <hr class="my-1">
  </h5>
  <ul class="list-unstyled mb-4">
    @each('reviews.single', $film->reviews, 'review', 'reviews.empty')
  </ul>
</div>
@endsection

resources/views/films/single.blade.php
<a href="{{ route('films.show', [$film]) }}" class="card text-secondary">
  <img class="card-img-top" src="/{{ $film->imgcover }}" alt="{{ $film->title }}">
  <div class="card-body">
    <h4 class="card-title">{{ $film->title }}</h4>
    <h6 class="card-subtitle">{{ $film->category->name }}</h6>
  </div>
  <div class="card-footer text-muted">
    <small>
    <i class="far fa-calendar mr-1"></i> {{ $film->release_date }}
      <div class="float-right">
        <i class="far fa-edit mr-1"></i> {{ $film->reviews->count() }}
      </div>
    </small>
  </div>
</a>