routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('films', 'FilmController');
Route::resource('categories', 'CategoryController', [
    'only' => ['index', 'show', 'create', 'store']
]);

Route::prefix('reviews')->group(function() {
  Route::get('create/{film}', 'ReviewController@create')->name('reviews.create');
  Route::post('create/{film}', 'ReviewController@store')->name('reviews.store');
});

Route::resource('reviews', 'ReviewController', [
  'except' => ['index', 'create', 'store']
]);

Route::prefix('comments')->group(function() {
  Route::get('create/{review}', 'CommentsController@create')->name('comments.create');
  Route::post('create/{review}', 'CommentsController@store')->name('comments.store');
  Route::get('delete/{comment}', 'CommentsController@destroy')->name('comments.delete');
});

Route::resource('comments', 'CommentsController', [
  'only' => ['edit', 'update', 'destroy']
]);

Route::prefix('users')->group(function() {
  Route::get('{user}', 'UserController@show')->name('users.show');
  Route::get('edit/{user}', 'UserController@edit')->name('users.edit');
  Route::post('{user}', 'UserController@update')->name('users.update');
});

Route::get('top', 'RankController@index')->name('ranks.index');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>{{ config('app.name', 'Laravel') }}</title>
  <!-- Scripts -->
  <script src="{{ asset('js/app.js') }}" defer></script>
  <!-- Fonts -->
  <link rel="dns-prefetch" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
  <div id="app">
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-laravel">
      <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
          <img src="{{ asset('logo.png') }}" width="30" height="30" class="d-inline-block align-top" alt="movie.pocket logo">
          {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">

          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
              <li>
                <a class="nav-link" href="{{ route('login') }}">Zaloguj się</a>
              </li>
              <li>
                <a class="nav-link" href="{{ route('register') }}">Rejestracja</a>
              </li>
            @else
              <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                  {{ auth()->user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{{ route('users.show', auth()->user()) }}">{{ __('Mój profil') }}</a>
                  @if(auth()->user()->isModerator())
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ route('films.create') }}">{{ __('Dodaj film') }}</a>
                    <a class="dropdown-item" href="{{ route('categories.create') }}">{{ __('Dodaj kategorię') }}</a>
                  @endif
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{ route('logout') }}"
                     onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                      {{ __('Wyloguj się') }}
                  </a>
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      @csrf
                  </form>
                </div>
              </li>
            @endguest
          </ul>
        </div>
      </div>
    </nav>
    <main role="main">
      @if (Session::has('success'))
        <div class="container">
          <div class="alert alert-info">{{ Session::get('success') }}</div>
        </div>
      @elseif (Session::has('error'))
        <div class="container">
          <div class="alert alert-danger">{{ Session::get('error') }}</div>
        </div>
      @endif
      @yield('content')
    </main>
  </div>
</body>
</html>